overwrite segments for removed code
Rich-Harris/magic-string pull request #147
Opened 2018-06-15 23:35 UTC by aleclarson

Removed ranges create two source map segments that refer to the same generated column. I consider this bloat if there isn't a good reason behind it. Generally, there shouldn't be segments for removed code (not including the segment for the characters after, whose source column is the removed range's end column).

What's your take on this, @mourner and/or @Rich-Harris?

Figured I should get feedback before writing any tests.

2018-06-18 08:34 UTC, mourner commented
@guybedford @lukastaegert what do you think? I'm not sure I fully understand the implications of this change for downstream users, so I'd refer to others for review.

2018-06-20 12:06 UTC, guybedford requested changes
Thanks for much @aleclarson for this PR.

This looks great in principle to me, but the test needs to be updated, and it would ideally come with another test that considers if there are any pathological edge cases of this behaviour - let me know if you can think of any interesting things that may come up here.

2018-06-20 12:06 UTC, guybedford commented on src/utils/Mappings.js
> +		let len = this.rawSegments.length;
Can we rather call this something more explanatory, perhaps:

```js
let checkDuplicateSegmentIndex = this.rawSegments.length - 1;
```

2018-06-20 12:06 UTC, guybedford commented on src/utils/Mappings.js
> +				if (len !== 0) {
This would then become `if (checkDuplpicateSegmentIndex !== -1)`

2018-06-20 12:06 UTC, guybedford commented on src/utils/Mappings.js
> +						len -= 1; // overwrite segments for removed code
These changes to `len` can be unnecessary if you just modify the last segment directly:

```js
this.rawSegments[checkDuplicateSegmentIndex] = [...];
```

2018-06-20 12:06 UTC, guybedford commented on src/utils/Mappings.js
> +				this.rawSegments[len++] = [this.generatedCodeColumn, sourceIndex, loc.line, loc.column];
The default path should be able to then revert to a `.push` as before.

2018-06-20 12:06 UTC, guybedford commented on src/utils/Mappings.js
> +				len = 0;
And this becomes `checkDuplicateSegmentIndex = -1` making it clearer this is a switch on the loop.

2026-09-10 01:06 UTC, antfu commented
Cleanup due to staleness. Thanks for the contribution

2026-09-10 01:06 UTC, closed without merging